const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  GOOGLE_SING_IN_START: 'GOOGLE_SING_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SING_IN_FAILURE: 'SING_IN_FAILURE',
  EMAIL_SING_IN_START: 'EMAIL_SING_IN_START',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SING_OUT_SUCCESS: 'SING_OUT_SUCCESS',
  SING_OUT_FAILURE: 'SING_OUT_FAILURE',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE'
}

export default UserActionTypes;